
import keyMirror from '../util/keyMirror';

export default keyMirror([
    'NAVIGATOR_JUMP_BACK',
    'NAVIGATOR_JUMP_FORWARD',
    'NAVIGATOR_JUMP_TO',
    'NAVIGATOR_PUSH',
    'NAVIGATOR_POP',
    'NAVIGATOR_REPLACE',
    'NAVIGATOR_REPLACE_AT_INDEX',
    'NAVIGATOR_REPLACE_PREVIOUS',
    'NAVIGATOR_IMMEDIATELY_RESET_ROUTE_STACK',
    'NAVIGATOR_POP_TO_ROUTE',
    'NAVIGATOR_POP_TO_TOP',
    'NAVIGATOR_REMOVE_ACTION'
]);
